---
title: "simulation"
output: html_document
---

```{r}
library(tidyverse)

set.seed(1)
```

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

```{r}
sim_mean_sd(30)
```

## Let's simulate a lot

Let's start with a for loop

```{r}

output= vector("list",100)

for (i in 1:100) 
  {
  
  output [[i]] = sim_mean_sd(30)
}

bind_rows(output)
```
Let's use a loop function.

```{r}
sim_results=
rerun(100, sim_mean_sd(30)) %>% 
  bind_rows()
```
Let's look at results

```{r}
sim_results %>% 
  ggplot(aes(x=mu_hat))+geom_density()

sim_results %>% 
  summarize(
    avg_samp_mean=mean(mu_hat),
    sd_samp_mean= sd(mu_hat)
  )

sim_results %>% 
  ggplot(aes(x=sigma_hat))+geom_density()
```
## Let's try other sample sizes.

```{r}

n_list=
  list(
    "n=30" =30,
    "n=60" =60,
    "n=120" =120,
    "n=240" =240
  )

output= vector ("list", length= 4)

for (i in 1:4) {
output[[1]]= rerun(100, sim_mean_sd(n_list[[1]])) %>% 
  bind_rows()
}
```

```{r}
sim_results_2=
tibble(
  sample_size= c(30,60,120, 240)
) %>% 
  mutate(
    output_lists=map(.x= sample_size, ~ rerun(1000, sim_mean_sd(.x))),
    estimate_df= map(output_lists,bind_rows)
    ) %>%
  select(-output_lists) %>% 
  unnest(estimate_df)
  
```
Do some data frame things.

```{r}
sim_results_2 %>% 
  mutate(
    sample_size=str_c("n=", sample_size)
  ) %>% 
  ggplot(aes(x=sample_size, y=mu_hat))+
  geom_violin()
```
```{r}
sim_results_2 %>% 
  group_by(sample_size) %>% 
  summarize(
    avg_samp_mean=mean(mu_hat),
    sd_samp_mean= sd(mu_hat)
  )
```

