---
title: "writing_functions"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
```

## Do something simple

```{r}
x_vec= rnorm(30, mean=5, sd=3)

(x_vec-mean(x_vec))/sd(x_vec)

```

I want a function to compute z-scores

```{r}

z_scores= function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
    
  z=(x-mean(x))/ sd(x)
  
  return (z)
  
z_scores(x_vec)
}
```

Try my function on some other things. THese should give errors.

```{r, error=TRUE}
z_scores(3)

z_scores("my name is Jeff")

z_scores (mtcars)

z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple Outputs

```{r}


mean_and_sd= function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x)< 3) {
    stop("Input must have at least three numbers")
  }
     
 mean_x=mean(x)
 sd_x=sd(x)
 
 tibble(
   mean=mean_x,
   sd= sd_x
 )

}
```

Check that the function works


```{r}
x_vec=rnorm (1000)
mean_and_sd(x_vec)
```

## Multiple Inputs

I'd like to do this with a function.

```{r}

sim_data= 
  tibble(
    x=rnorm(n=100, mean=4, sd=3)
  )
sim_data %>% 
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
```

```{r}
sim_mean_sd= function (samp_size, mu = 3, sigma = 4){

  sim_data= 
    tibble(
     x=rnorm(n=samp_size, mean=mu, sd=sigma)
  )
  
sim_data %>% 
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
}

sim_mean_sd(samp_size=100,mu=6, sigma= 3)
sim_mean_sd(mu=6, samp_size= 100, sigma=3)

sim_mean_sd(samp_size=100)
```


